version: '2'

services:
  web:
    build: ./web/.
    # container_name: web
    expose:
      - "8000"
    networks:
      - front-tier
      - back-tier
    volumes:
      - /media/lee/78b3df3f-70e8-4101-b632-d3b341665d5f/dev/dockerizing-django-ng2/web:/usr/src/app
      
    env_file: .env
    depends_on:
       - postgres
    command: /usr/local/bin/gunicorn web.wsgi:application -w 2 -b :8000

  nginx:
    build: ./nginx/.
    ports:
      - "80:80"
    volumes:
      - /media/lee/78b3df3f-70e8-4101-b632-d3b341665d5f/dev/dockerizing-django-ng2/nginx/angular2:/usr/share/nginx/angular2
    networks:
      - front-tier

  postgres:
    image: postgres:latest
    # container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - back-tier 
    
  redis:
    image: redis:latest
    # container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - back-tier 
      
volumes: 
  pgdata:
  redisdata:

networks:
  front-tier:
  back-tier: